spring:
  application:
    name: petcare
  datasource:
    url: jdbc:mysql://localhost:3306/petcaredb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration,db/data
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update